const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const panel={innerHTML:'',querySelectorAll:()=>[]};
const coins=[['a','WIN','one'],['b','LOSE','one'],['c','OLD','one'],['d','NONE','one'],['e','ONLYUP','two'],['f','ONLYDOWN','three']].map(([id,ticker,cat])=>({id,ticker,cat,name:ticker,gecko:id}));
const quote=(d7,d24,stale=false)=>({price_change_percentage_7d_in_currency:d7,price_change_percentage_24h:d24,stale,sparkline_in_7d:{price:[1,2,3]}});
const ctx=vm.createContext({coins,mkt:{a:quote(10,-2),b:quote(-20,30),c:quote(1000,1000,true),d:quote(null,null),e:quote(4,4),f:quote(-5,-5)},priceSeries:d=>d?.sparkline_in_7d?.price,catList:()=>['one','two','three'].map(id=>({id})),catLabelOf:c=>c,document:{getElementById:()=>panel}});ctx.window=ctx;
vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../compare-chart.js'),'utf8'),ctx);
ctx.renderCompareChart();
const cards=()=>[...panel.innerHTML.matchAll(/<section class="category-movers">([\s\S]*?)<\/section>/g)].map(m=>m[1]);
assert(cards()[0].includes('2/4개 집계'));assert(cards()[0].includes('<strong>WIN</strong><b>+10.0%'));assert(cards()[0].includes('<strong>LOSE</strong><b>-20.0%'));assert(cards()[1].includes('하락 종목 없음'));assert(cards()[2].includes('상승 종목 없음'));
assert(cards()[0].indexOf('comparePick(&quot;a&quot;)')<cards()[0].lastIndexOf('comparePick(&quot;b&quot;)'));
ctx.setCompareRanking('24h','asc');assert(cards()[0].includes('<strong>LOSE</strong><b>+30.0%'));assert(cards()[0].includes('<strong>WIN</strong><b>-2.0%'));assert(panel.innerHTML.includes('최근 24시간'));
const ranked=cards()[0].split('compare-cat-ranked')[1];assert(ranked.indexOf('WIN')<ranked.indexOf('LOSE'));assert(ranked.indexOf('LOSE')<ranked.indexOf('OLD'));
ctx.compareClear();assert(panel.innerHTML.includes('비교할 종목을 선택하세요'));
ctx.coins[0].ticker='<script>bad</script>';ctx.renderCompareChart();assert(!panel.innerHTML.includes('<script>bad</script>'));
console.log('PASS: per-category gain/loss leaders, named intervals, stale/missing exclusions, one-sided categories, sorting, clear selection and escaping.');
ctx.setCompareView('all');assert(panel.innerHTML.includes('data-chart-scope="all"'));
const lineCount=()=>[...panel.innerHTML.matchAll(/<polyline /g)].length;
assert.equal(lineCount(),6);ctx.toggleScopedCompare('all','a');assert.equal(lineCount(),5);
ctx.setCompareView('categories');assert.equal([...panel.innerHTML.matchAll(/data-chart-scope="cat:/g)].length,3);assert.equal(lineCount(),6);
const scope=name=>panel.innerHTML.split(`data-chart-scope="${name}"`)[1].split('</section>')[0];
assert.equal([...scope('cat:one').matchAll(/<polyline /g)].length,4);assert.equal([...scope('cat:two').matchAll(/<polyline /g)].length,1);
ctx.toggleScopedCompare('cat:one','a');assert.equal([...scope('cat:one').matchAll(/<polyline /g)].length,3);assert.equal([...scope('cat:two').matchAll(/<polyline /g)].length,1);
ctx.setScopedCompare('cat:one',true);assert.equal([...scope('cat:one').matchAll(/<polyline /g)].length,4);
ctx.setCompareView('selected');assert.equal(lineCount(),0);ctx.toggleScopedCompare('selected','b');assert.equal(lineCount(),1);
ctx.setCompareView('all');assert.equal(lineCount(),5);ctx.setCompareView('selected');assert.equal(lineCount(),1);
ctx.setScopedCompare('selected',true);assert.equal(lineCount(),6);ctx.setScopedCompare('selected',false);assert.equal(lineCount(),0);
ctx.mkt.a.sparkline_in_7d.price=Array.from({length:200},(_,i)=>i===199?100:1);ctx.setCompareView('all');ctx.setScopedCompare('all',true);assert(panel.innerHTML.includes('9900.0%'));
assert(panel.innerHTML.includes('stroke-dasharray="6 4"'));assert(!panel.innerHTML.includes('NaN'));
console.log('PASS: overview/custom/category multicharts, independent per-chart ticker controls, clear/restore, stale lines and full history endpoints.');
