const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const nodes=new Map(),storage=new Map();const el=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,innerHTML:'',textContent:'',addEventListener(){},matches(){return false}});return nodes.get(id)};
const ctx=vm.createContext({console,URL,Date,AbortSignal,location:{protocol:'file:',origin:'null'},window:{addEventListener(){},scrollTo(){}},setTimeout,setInterval:()=>1,document:{activeElement:null,hidden:false,getElementById:el,querySelector:()=>({}),querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}});
for(const [,src,code]of html.matchAll(/<script(?: src="([^"]+)")?>([\s\S]*?)<\/script>/g)){if(code.includes('startAutomatic();'))continue;vm.runInContext(src?fs.readFileSync(path.join(root,src),'utf8'):code,ctx);}
const run=s=>vm.runInContext(s,ctx);
run('load();initFarmingPairs()');assert.equal(run('farmingPairs.length'),0);
run("selectFarmingVenue('risex')");assert.equal(run('farmingPairs.length'),0);assert.equal(run('selectedVenue'),'risex');
run("selectFarmingVenue('risex')");assert.equal(run('selectedVenue'),null);
run("selectFarmingVenue('risex');selectFarmingVenue('truenorth')");assert.equal(run('farmingPairs.length'),1);assert.equal(run('farmingPairs[0].long.venue'),'RiseX');assert.equal(run('farmingPairs[0].short.venue'),'Truenorth');assert.equal(run('pairMetrics(farmingPairs[0]).net'),null);
run("selectFarmingVenue('arcus');selectFarmingVenue('risex')");assert.equal(run('farmingPairs.length'),1);assert.equal(run('selectedVenue'),'arcus');
run("selectFarmingVenue('entropy');selectFarmingVenue('hello');selectFarmingVenue('mnx');selectFarmingVenue('pacifica');selectFarmingVenue('qfex');selectFarmingVenue('quote');selectFarmingVenue('n1')");
assert.equal(run('activeFarmingPairs().length'),5);assert.equal(run('venueUsage().filter(v=>v.active).length'),10);assert(!run('renderVenueRoster()').includes('href='));
run("farmingPairs[0].reason='Preserved';swapFarmingSides(farmingPairs[0].id)");assert.equal(run('farmingPairs[0].long.venue'),'Truenorth');
run('unpairFarming(farmingPairs[0].id)');assert.equal(run('activeFarmingPairs().length'),4);assert.equal(run('farmingPairs[0].reason'),'Preserved');assert.equal(run('farmingPairs[0].archived'),true);
run("selectFarmingVenue('risex');selectFarmingVenue('truenorth');save();load();initFarmingPairs()");assert.equal(run('activeFarmingPairs().length'),5);assert.equal(run('farmingPairs.length'),6);
run("farmingPairs=[{id:'p1',long:{},short:{}},{id:'p2',long:{},short:{}}]");

run("farmingPairs[0]={id:'pair-1',name:'Pair',ticker:'BTC',long:{venue:'A',quantity:2,mark:100,points7:10,cost7:2},short:{venue:'B',quantity:2,mark:101},reason:'Keep thesis',conviction:5}");
assert.equal(run('pairMetrics(farmingPairs[0]).net'),0);assert.equal(run('pairMetrics(farmingPairs[0]).gross'),402);assert.equal(run('pairEfficiency(farmingPairs[0].long)'),.2);assert.equal(run('pairEfficiency(farmingPairs[0].short)'),null);
run('farmingPairs[0].short.quantity=1');assert.equal(run('pairMetrics(farmingPairs[0]).net'),1);assert.equal(run('pairMetrics(farmingPairs[0]).imbalance'),50);
run("farming=[{id:'hl-btc',name:'Hyperliquid',source:'hyperliquid',ticker:'BTC',quantity:2,side:'short',updatedAt:Date.now()}];perpFeed={data:[{symbol:'BTC',mark:110}]};farmingPairs[0].short.positionId='hl-btc'");assert.equal(run('pairMetrics(farmingPairs[0]).net'),0);assert.equal(run('pairMetrics(farmingPairs[0]).gross'),420);
run("farming[0].side='long'");assert(run('validateFarmingPair(farmingPairs[0])'));assert.equal(run('pairMetrics(farmingPairs[0]).net'),null);
run("farming[0].side='short';farming[0].ticker='ETH'");assert(run('validateFarmingPair(farmingPairs[0])'));assert.equal(run('pairMetrics(farmingPairs[0]).net'),null);
run("farming[0].ticker='BTC';farmingPairs[1].short.positionId='hl-btc'");assert(run('validateFarmingPair(farmingPairs[0])'));
run("delete farmingPairs[1].short.positionId;farming[0].closed=true");assert.equal(run('pairMetrics(farmingPairs[0]).net'),null);
run("farming[0].closed=false;save();farmingPairs=null;load();initFarmingPairs();setTab('farming')");assert.equal(run('farmingPairs[0].reason'),'Keep thesis');assert.equal(run('farmingPairs[0].conviction'),5);assert(el('pair-board').innerHTML.includes('LONG'));assert.equal(el('pair-board').hidden,false);
run('farmingPairs=[];save();load();initFarmingPairs()');assert.equal(run('farmingPairs.length'),0,'unpaired books stay empty');
run("setTab('options')");assert.equal(el('pair-board').hidden,true);
assert.equal(run("FARMING_VENUES.length"),10,'N1 brings the roster to ten venues');
run("farmingPairs=[{long:{venue:'N1'},short:{}}]");
assert.equal(run("venueUsage().find(v=>v.key==='n1').active"),true,'typing N1 activates the N1 venue');
run("farmingPairs[0].long.venue='RiseN1X'");
assert.equal(run("venueUsage().find(v=>v.key==='n1').active"),false,"a venue merely containing 'n1' must not false-match the short alias");
run("farmingPairs[0].long.venue='A'");
console.log('PASS: two-click creation, selection cancellation, ten unique venues/five pairs, archive/re-pair, direction swap, persistence, hedge calculations, connected positions and validation.');
run("farmingPairs=[{id:'wallet-pair',name:'A × B',long:{venue:'A'},short:{venue:'B'},reason:'Keep'}];savePairWallet('wallet-pair','long','Rabby main · 0x123');savePairWallet('wallet-pair','short','Phantom trading');load()");
assert.equal(run('farmingPairs[0].long.wallet'),'Rabby main · 0x123');assert.equal(run('farmingPairs[0].short.wallet'),'Phantom trading');
run("swapFarmingSides('wallet-pair')");assert.equal(run('farmingPairs[0].short.venue'),'A');assert.equal(run('farmingPairs[0].short.wallet'),'Rabby main · 0x123');
run("savePairWallet('wallet-pair','short','<img src=x onerror=alert(1)>');renderPairBoard()");assert(el('pair-board').innerHTML.includes('&lt;img src=x onerror=alert(1)&gt;'));assert(!el('pair-board').innerHTML.includes('<img src=x'));
run("document.activeElement={matches:()=>true};savePairWallet('wallet-pair','long','Editing');");const before=el('pair-board').innerHTML;run('renderPairBoard()');assert.equal(el('pair-board').innerHTML,before);
run("document.activeElement=null;unpairFarming('wallet-pair');load()");assert.equal(run('farmingPairs[0].long.wallet'),'Editing');assert.equal(run('farmingPairs[0].archived'),true);
console.log('PASS: wallet autosave/reload, per-venue direction swap, safe markup, edit focus retention and archived wallet preservation.');
